---
driver:
  name: docker
platforms:
  - name: debianbullseye
    image: debian:bullseye
    dockerfile: Dockerfile-debian-bullseye.j2
    privileged: true
    override_command: false
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
       git_remembrall_repos:
         'git-remembrall':
           repo: 'https://github.com/zerwes/git-remembrall.git'
           dest: /var/tmp/git-remembrall
           ignorebranches:
             - test
             - abc
           relevantfiles:
             - molecule
verifier:
  name: ansible
