---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  vars:
    git_remembrall_script_path: /usr/local/bin/git_remembrall.sh
    compare_lines:
      - "[git git-remembrall (https://github.com/zerwes/git-remembrall.git)] issues on branch origin/testbranch4check"
      - "Hello zerwes@users.noreply.github.com"
  tasks:
  - name: check syntax
    ansible.builtin.shell: "bash -v {{ git_remembrall_script_path }}"
  - name: "run {{ git_remembrall_script_path }}"
    ansible.builtin.command: "{{ git_remembrall_script_path }} -m"
    register: _git_remembrall_script_out
  - name: debug _git_remembrall_script_out
    ansible.builtin.debug:
      var: _git_remembrall_script_out
  - name: check _git_remembrall_script_out
    ansible.builtin.assert:
      that: _git_remembrall_script_out.stdout_lines[item] == compare_lines[item]
    with_items:
      - 0
      - 1
