---
name: molecule test
on:
  pull_request:
  push:
  schedule:
    - cron: "10 5 * * 1"
jobs:
  molecule:
    name: ansible
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - latest
          - pinned
          - legacy
        distro:
          - debian11
          - debian12
        include:
          - ansible: latest
            pip3deps: 'ansible molecule "molecule-plugins[docker]" yamllint ansible-lint "requests" "urllib3"'
            pythonversion: 3.11
          - ansible: pinned
            pip3deps: '"ansible==10.4.0" "molecule-plugins[docker]" "yamllint==1.35.1" "ansible-lint==24.9.0" "requests==2.31.0" "urllib3==2.2.2"'
            pythonversion: 3.11
          - ansible: legacy
            pip3deps: '"ansible==2.9.27" "molecule[docker,lint]==3.2.3" "yamllint==1.24.2" "ansible-lint==4.2.0" "requests<2.29" "urllib3<2"'
            pythonversion: 3.9

    steps:
      - uses: actions/checkout@v4
        with:
          path: 'zerwes.gitremembrall'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pythonversion }}

      - name: Install test dependencies.
        run: pip3 install ${{ matrix.pip3deps }}

      - name: run molecule tests
        run: molecule test
        working-directory: zerwes.gitremembrall
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
